import { Download, FileCode, Maximize2 } from 'lucide-react';

interface OutputItem {
  id: string;
  stepNumber: number;
  title: string;
  badge: string;
  badgeColor: string;
  gsd: string;
  description: string;
  imageSrc: string;
  pngDownload: string;
  geotiffDownload?: string;
  metrics: { label: string; value: string }[];
}

export const VerticalOutputViewer: React.FC = () => {
  const outputs: OutputItem[] = [
    {
      id: 'opt-cloudy',
      stepNumber: 1,
      title: '1. Live Optical Input (Cloudy Sentinel-2)',
      badge: 'Input Raw (10m)',
      badgeColor: 'bg-amber-100 text-amber-800 border-amber-300',
      gsd: '10.0m GSD',
      description:
        'Live optical acquisition from Google Earth Engine (Copernicus Sentinel-2 L2A). Obscured by cloud formations and high altitude cirrus over mountainous terrain.',
      imageSrc: '/outputs/1_optical_cloudy.png',
      pngDownload: '/outputs/1_optical_cloudy.png',
      metrics: [
        { label: 'Ground Resolution', value: '10.0m / pixel' },
        { label: 'Cloud Obstruction', value: '18.4% (Exceeds 10% threshold)' },
        { label: 'Spectral Bands', value: 'B2 (Blue), B3 (Green), B4 (Red), B8 (NIR)' },
        { label: 'Sensor', value: 'Sentinel-2 MSI' },
      ],
    },
    {
      id: 'sar-radar',
      stepNumber: 2,
      title: '2. Sentinel-1 SAR Radar (VV Polarization)',
      badge: 'Radar Penetration (10m)',
      badgeColor: 'bg-slate-100 text-slate-800 border-slate-300',
      gsd: '10.0m GSD',
      description:
        'C-Band Synthetic Aperture Radar backscatter image. Microwaves completely penetrate clouds, fog, and atmospheric turbulence, providing direct topographic structural data.',
      imageSrc: '/outputs/2_sentinel1_sar.png',
      pngDownload: '/outputs/2_sentinel1_sar.png',
      metrics: [
        { label: 'Ground Resolution', value: '10.0m / pixel' },
        { label: 'Radar Band', value: 'C-Band (5.405 GHz)' },
        { label: 'Polarisation Mode', value: 'VV (Vertical Transmit / Vertical Receive)' },
        { label: 'Cloud Penetration', value: '100% Unaffected by Atmospheric Water' },
      ],
    },
    {
      id: 'auraclear-clean',
      stepNumber: 3,
      title: '3. AuraClear Reconstructed (Cloud-Free 10m)',
      badge: 'Inpainted Output (10m)',
      badgeColor: 'bg-blue-100 text-blue-800 border-blue-300',
      gsd: '10.0m GSD',
      description:
        'AuraClear 10-channel U-Net deep fusion result. Cloud regions are inpainted with radar structural guidance while 100% of authentic clear ground pixels are preserved without chromatic distortion.',
      imageSrc: '/outputs/3_auraclear_cleansed.png',
      pngDownload: '/outputs/3_auraclear_cleansed.png',
      geotiffDownload: '/outputs/cloud_free.tif',
      metrics: [
        { label: 'Ground Resolution', value: '10.0m / pixel' },
        { label: 'Model Architecture', value: '10-Channel Fusion U-Net (AuraClear)' },
        { label: 'Blending Method', value: 'Masked Inpainting (Ground Preserved)' },
        { label: 'Residual Cloud', value: '0.0% (Clean Surface Reflectance)' },
      ],
    },
    {
      id: 'super-resolved',
      stepNumber: 4,
      title: '4. AuraClear-SR Sub-4m Super-Resolved Output',
      badge: 'Super-Resolved (3.33m Sub-4m)',
      badgeColor: 'bg-emerald-100 text-emerald-800 border-emerald-300',
      gsd: '3.33m GSD (Sub-4m)',
      description:
        'Final 3x sub-pixel super-resolved output generated by AuraClear-SR. Resolves sub-4m high-frequency terrain features, roads, ridges, and river boundaries with 9x pixel density multiplier.',
      imageSrc: '/outputs/4_super_resolved_sub4m.png',
      pngDownload: '/outputs/4_super_resolved_sub4m.png',
      geotiffDownload: '/outputs/cloud_free.tif',
      metrics: [
        { label: 'Ground Resolution (GSD)', value: '3.33m / pixel (Sub-4m Tier)' },
        { label: 'Pixel Density Multiplier', value: '9x (3x width × 3x height)' },
        { label: 'Image Dimensions', value: '1152 × 1152 pixels (300 DPI)' },
        { label: 'Radiometric Calibration', value: 'Natural True-Color sRGB Tone Curve' },
      ],
    },
  ];

  return (
    <div className="w-full bg-white border border-slate-200/90 rounded-lg shadow-sm p-4 sm:p-6 select-none space-y-6">
      {/* Header bar */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between pb-3 border-b border-slate-200 gap-2">
        <div>
          <h2 className="text-[17px] font-bold text-slate-900 tracking-tight flex items-center gap-2">
            <span>Pipeline Generated Outputs</span>
            <span className="text-[11px] font-semibold text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-200">
              4 Sequential Stages
            </span>
          </h2>
          <p className="text-[12.5px] text-slate-500 mt-0.5">
            Full-width readable image inspection for each stage of the SAR-guided super-resolution pipeline.
          </p>
        </div>

        <div className="flex items-center space-x-2">
          <a
            href="/outputs/cloud_free.tif"
            download="GeoLens_Complete_Package.tif"
            className="px-3.5 py-1.5 bg-[#1a56db] hover:bg-[#1546b3] text-white text-[12px] font-semibold rounded-md shadow-xs flex items-center space-x-1.5 transition-colors"
          >
            <FileCode className="h-3.5 w-3.5" />
            <span>Export All (GeoTIFF)</span>
          </a>
        </div>
      </div>

      {/* VERTICAL STACK OF READABLE FULL-WIDTH IMAGES (NO 2x2 SQUARES) */}
      <div className="space-y-8">
        {outputs.map((item) => (
          <div
            key={item.id}
            className="bg-slate-50/60 border border-slate-200 rounded-lg overflow-hidden shadow-xs hover:shadow-sm transition-shadow"
          >
            {/* Output Item Header */}
            <div className="px-4 py-3 bg-white border-b border-slate-200 flex flex-wrap items-center justify-between gap-2">
              <div className="flex items-center space-x-2.5">
                <span className="text-[14px] font-bold text-slate-800 tracking-tight">
                  {item.title}
                </span>
                <span
                  className={`text-[11px] font-semibold px-2 py-0.5 rounded border ${item.badgeColor}`}
                >
                  {item.badge}
                </span>
              </div>

              {/* Action Buttons for this Image */}
              <div className="flex items-center space-x-2">
                <a
                  href={item.pngDownload}
                  download={`GeoLens_Stage_${item.stepNumber}_${item.id}.png`}
                  className="px-3 py-1 bg-white hover:bg-slate-50 text-slate-700 border border-slate-300 rounded text-[11.5px] font-medium transition-colors flex items-center space-x-1 shadow-2xs"
                >
                  <Download className="h-3.5 w-3.5 text-slate-500" />
                  <span>Download PNG</span>
                </a>

                {item.geotiffDownload && (
                  <a
                    href={item.geotiffDownload}
                    download="GeoLens_Output_EPSG4326.tif"
                    className="px-3 py-1 bg-[#eff6ff] hover:bg-[#dbeafe] text-[#1a56db] border border-blue-200 rounded text-[11.5px] font-medium transition-colors flex items-center space-x-1 shadow-2xs"
                  >
                    <FileCode className="h-3.5 w-3.5 text-[#1a56db]" />
                    <span>Export GeoTIFF</span>
                  </a>
                )}
              </div>
            </div>

            {/* Large Readable Full-Width Image Container */}
            <div className="p-4 bg-slate-900/95 flex justify-center items-center overflow-hidden relative group">
              <img
                src={item.imageSrc}
                alt={item.title}
                className="w-full max-w-4xl max-h-[580px] object-contain rounded shadow-lg bg-black"
                loading="eager"
              />

              {/* Resolution Watermark */}
              <div className="absolute bottom-6 right-6 bg-black/80 backdrop-blur-xs text-white px-2.5 py-1 rounded text-[11px] font-mono border border-white/20">
                {item.gsd}
              </div>

              {/* Fullscreen inspect icon */}
              <a
                href={item.imageSrc}
                target="_blank"
                rel="noreferrer"
                title="Open full resolution in new tab"
                className="absolute top-6 right-6 p-2 bg-black/60 hover:bg-black/90 text-white rounded opacity-0 group-hover:opacity-100 transition-opacity"
              >
                <Maximize2 className="h-4 w-4" />
              </a>
            </div>

            {/* Description & Technical Ground Metrics Table */}
            <div className="p-4 bg-white border-t border-slate-200 space-y-3">
              <p className="text-[12.5px] text-slate-600 leading-relaxed">
                {item.description}
              </p>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 pt-2 border-t border-slate-100 text-[11.5px]">
                {item.metrics.map((m, mIdx) => (
                  <div key={mIdx} className="bg-slate-50 p-2 rounded border border-slate-100">
                    <span className="text-slate-400 block text-[10.5px] font-medium uppercase tracking-wider">
                      {m.label}
                    </span>
                    <span className="font-semibold text-slate-800 mt-0.5 block truncate">
                      {m.value}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
